### ISSUE TITLE
code.google.com error

### ISSUE THREAD

**Issue by jmervine** [tomsteele/dmv#5]
Getting...

```
github.com/tomsteele/dmv (download)
package code.google.com/p/goauth2/oauth: unable to detect version control system for code.google.com/ path
```

Looks like https://github.com/tomsteele/dmv/blob/master/oauth2.go#L7 needs to be updated to the following...

```
    "github.com/google/goauth2/oauth"
```

**Comment by tomsteele** [comment]
cool you want to submit a PR?

**Comment by jmervine** [comment]
Actually, it looks like I was wrong about it being github.com/google/goauth2/oauth, but rather they've moved to `google.golang.org/api/oauth2/v{1,2}` and changed the implementation. I ended up finding another solution and sadly, don't have time to dig in to this right now.

**Comment by tomsteele** [comment]
I was able to grab the old package and pull it in as a local dep now.
